#pragma once
#include "pch.h"
#include <string>
#include <vector>

namespace SpongeBob {
	static const std::vector<std::string> EPISODE_LIST{
		"01a help wanted",
		"01b reef blower",
		"01c tea at the treedome",
		"02a bubblestand",
		"02b ripped pants",
		"03a jellyfishing",
		"03b plankton",
		"04a naughty naughtical neighbors",
		"04b boating school",
		"05a pizza delivery",
		"05b home sweet pineapple",
		"06a mermaid man and barnacle boy",
		"06b pickles",
		"07a hall monitor",
		"07b jellyfish jam",
		"08a sandys rocket",
		"08b squaky boots",
		"09a nature pants",
		"09b opposite day",
		"10a culture shock",
		"10b fun",
		"11a musclebob buffpants",
		"11b squidward the unfriendly ghost",
		"12a the chaperone",
		"12b employee of the month",
		"13a scaredy pants",
		"13b i was a teenage gary",
		"14a sb-129",
		"14b karate choppers",
		"15a sleepy time",
		"15b suds",
		"16a valetiones day",
		"16b the paper",
		"17a arrgh",
		"17b rock bottom",
		"18a texas",
		"18b walking small",
		"19a fools in april",
		"19b neptunes spatula",
		"20a hooky",
		"20b medmaid man and barnacle boy ii",
		"21a your shoes untied",
		"21b squids day off",
		"22a something smells",
		"22b bossy boots",
		"23a big pink loser",
		"23b buble buddy",
		"24a dying for pie",
		"24b imitation krabs",
		"25a wormy",
		"25b patty hype",
		"26a grandmas kisses",
		"26b squidville",
		"27a prehibernation week",
		"27b life of crime",
		"28 christmas who",
		"29a survival of the idiots",
		"29b dumped",
		"30a no free rides",
		"30b im your biggest fanatic",
		"31a mermaid man and barnacle boy iii",
		"31b squirrel jokes",
		"32a pressure",
		"32b the smoking peanut",
		"33a shanghaied",
		"33b gary takes a bath",
		"34a welcome to the chum bucket",
		"34b frankendoodle",
		"35a the secret box",
		"35b band geeks",
		"36a graveyard shift",
		"36b krusty love",
		"37a procrastination",
		"37b im with stupid",
		"38a sailor mouth",
		"38b artist unknown",
		"39a jellyfish hunter",
		"39b the fry cook games",
		"40a squid on strike",
		"40b sandy sponegbob and the worm",
		"41a the algaes always greener",
		"41b spongeguard on duty",
		"42a club spongebob",
		"42b my pretty seahorse",
		"43a just one bite",
		"43b the bully",
		"44a nasty patty",
		"44b idiot box",
		"45a mermaid man and barnacle boy iv",
		"45b doing time",
		"46a snowball effect",
		"46b one krabs trash",
		"47a as seen on tv",
		"47b can you spare a dime",
		"48a no weenied allowed",
		"48b suilliam retrurns",
		"49a krab borg",
		"49b rock a bye bivalve",
		"50a wet painters",
		"50b krusty krab training video",
		"51 party pooper pants",
		"52a chocolate with nuts",
		"52b mermaid man and barnacle boy v",
		"53a new student starfish",
		"53b clams",
		"54 ugh",
		"55a the great snail race",
		"55b mid life crustacean",
		"56a born again krabs",
		"56b i had an accident",
		"57a krabby land",
		"57b the camping episode",
		"58a missing identity",
		"58b planktons army",
		"59 the sponge who could fly",
		"60a spongebob meets the strangler",
		"60b pranks a lot"
	};

	static const int EPISODE_COUNT = 117;
}
